In [1]:
import numpy, pandas

In [2]:
train = open('train_data_for_test.dat', encoding='utf-8', mode='r')
train = [l.split(' ') for l in train.readlines()]
train_data = [{'u_id': t[0], 'i_id': t[1], 'score': t[2], 'word': t[3], 'each': t[4:-1]}
              for t in train]

user_list = list(set([t['u_id'] for t in train_data]))
item_list = list(set([t['i_id'] for t in train_data]))

In [3]:
user_item_df = pandas.DataFrame(numpy.zeros([len(user_list), len(item_list)]), index=user_list, columns=item_list)

In [4]:
for i in train_data:
    user_item_df.at[i['u_id'], i['i_id']] = i['score']

In [5]:
user_item_matrix = user_item_df.as_matrix()

In [6]:

user_item_matrix


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
U, S, V_t = numpy.linalg.svd(user_item_matrix, full_matrices=False)

In [12]:
A = [[5,5,0,5],[5,0,3,4],[3,4,0,3],[0,0,5,3],[5,4,4,5],[5,4,5,5]]
numpy.linalg.svd(A, full_matrices=False)

(array([[-0.44721867, -0.53728743, -0.00643789, -0.50369332],
        [-0.35861531,  0.24605053,  0.86223083, -0.14584826],
        [-0.29246336, -0.40329582, -0.22754042, -0.10376096],
        [-0.20779151,  0.67004393, -0.3950621 , -0.58878098],
        [-0.50993331,  0.05969518, -0.10968053,  0.28687443],
        [-0.53164501,  0.18870999, -0.19141061,  0.53413013]]),
 array([17.71392084,  6.39167145,  3.09796097,  1.32897797]),
 array([[-0.57098887, -0.4274751 , -0.38459931, -0.58593526],
        [-0.22279713, -0.51723555,  0.82462029,  0.05319973],
        [ 0.67492385, -0.69294472, -0.2531966 ,  0.01403201],
        [ 0.41086611,  0.26374238,  0.32859738, -0.80848795]]))